### ISSUE TITLE
FIPS Certified Hashing Algorithm

### ISSUE THREAD

**Issue by mmanela** [mmanela/chutzpah#184]
<b>ja9urc311[CodePlex]</b> <br />Would it be possible to switch out the MD5CryptoServiceProvider in Chutzpah.Utility.Hasher to a FIPS Certified provider (i.e. AesCryptoServiceProvider, SHA256CryptoServiceProvider, SHA384CryptoServiceProvider, and SHA512CryptoServiceProvider)? When FIPSAlgorithmPolicy
 is enabled in the registry, Chutzpah doesn't run. Thanks.

**Comment by Jweber719** [comment]
Was this issue closed because it was too big to implement.  Working in the government sector we don't have a choice on security settings and FIPs is strictly enforced.  We were in an open environment and using Chutzpah exclusively for our unit testing, but now that we were forced into a secure environment, we can't run the tests.  DId anyone have a solution for this?

**Comment by mmanela** [comment]
Thanks for following up. I had went through and closed old issues since I wasn't sure the status of them. If this is still an issue for you I can re-open.

**Comment by Jweber719** [comment]
Hi Matthew,

It was an issue but I pulled an older version and updated the Hasher.cs
file to use SHA1 instead of MD5 and was able to compile and run all of our
tests in the restricted environment.  Thanks for reaching out so quickly!

Jason

On Jan 25, 2017 6:42 PM, "Matthew Manela" <notifications@github.com> wrote:

Thanks for following up. I had went through and closed old issues since I
wasn't sure the status of them. If this is still an issue for you I can
re-open.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/mmanela/chutzpah/issues/184#issuecomment-275268268>,
or mute
the thread
