### ISSUE TITLE
test discovery is slow

### ISSUE THREAD

**Issue by ariovistus** [mmanela/chutzpah#332]
is there a way to disable automatic test discovery? On my box it is taking upwards of 6 seconds - a bit longer than it is taking to actually run the tests, and I find it incredibly annoying to have to pointlessly wait after each edit to my test file.

**Comment by mmanela** [comment]
That is odd it is taking so long. In the coming version 4.0, there is a new feature that should help that lets you batch your test files into one test harness. This improves the perf in many cases.

Otherwise, you can install the Chutzpah context menu extension instead of the test adapter which doesn't do the automatic discovery.

**Comment by ariovistus** [comment]
its likely due to the crappy workstation I am required to use.
