### ISSUE TITLE
Chutzpah failing to find tests

### ISSUE THREAD

**Issue by ameyagholkar** [mmanela/chutzpah#348]
Hi,
Our project is using Typescript, Qunit and Sinon. we have installed the latest VS2013 Chutzpah tools. However, whenever we try to run any test file on the browser using the right-click context menu - we see no test executions. 

We looked at the source code for the html test runner that gets loaded and I can see that the @@TestJSFile@@ attribute fails to populate. 

Note: I am running VS2013 on Windows 10.

Link to the project structure for the Tests - https://github.com/Microsoft/ApplicationInsights-JS/tree/master/JavaScript/JavaScriptSDK.Tests

Link to the chutzpah's json settings - https://github.com/Microsoft/ApplicationInsights-JS/blob/master/JavaScript/JavaScriptSDK.Tests/chutzpah.json

FYI - @scsouthw, @MaxShehovtsov

**Comment by mmanela** [comment]
The issue here is you are never telling Chutzpah anything about the compiled files. You give it .ts files only. You need to configure Chutzpah to know where to find your .js files (https://github.com/mmanela/chutzpah/wiki/Compile-Setting). This works in most cases but in your case its a bit trickier. 

Since you are compiling all your files into one large version it makes it hard for Chutzpah. Using the following settings I got it to work (for the checkinTests.js by including it explicitly) but this has drawbacks. Every time you run one file's tests it will execute ALL tests. This is fine if you are running all the tests in one batch but if you just want to run one file it can be undesirable.

```
{
    "Framework": "qunit",
    "References": [
        { "Path": "External/Sinon-1.7.3.js" },
        { "Path": "Selenium/JSLitmus.js" },
        { "Path": "E2ETests/testSnippet.js" },
        { "Path": "Selenium/checkinTests.js" }
    ],
    "EnableTestFileBatching": true,
    "CodeCoverageExcludes": [ "*Tests*" ]
}
```

**Comment by mmanela** [comment]
Closing issue. Original poster can re-open if not fixed.
