### ISSUE TITLE
Chutzpah fails when there're many node_modules files in a project.

### ISSUE THREAD

**Issue by viskin** [mmanela/chutzpah#384]
I have a project that worked previously, but **as I added node_modules folder** to the project with many js files in it, Chutzpah started to fail.
No other changes performed, and **node_modules folder not included in Chutzpah.json file**.

The cause of failure is unknown to me, this may be large amount of files, or some specific js file that when attached to project causes Chutzpah to fail. There is no obvious error in trace file. In both cases, the file is **not included** to Chutzpah.json.

Steps to reproduce:

- Use latest Chutzpah adapter plugin.
- Git Clone [kendo-pouchdb project](https://github.com/terikon/kendo-pouchdb).
- Run 'npm install' to install dependencies.
- Open /KendoPouchDB.sln file.
- Open test explorer.
- The test explorer will fail, with 'Error: One or more errors occurred.' in chutzpah.log.

Now to make Chutzpah work again:
- Close the solution.
- Go to node_modules folder.
- Remove all folders that contain 'grunt' in their names:
  - grunt
  - grunt-contrib-jasmine
  - grunt-contrib-jshint
  - grunt-contrib-uglify
  - grunt-kendo-lint
  - load-grunt-tasks
- Open the solution.
- Go to test explorer.
- Tests will appear!

*Visual Studio 2013, Chutzpah Test Adapter 4.0.3.*

**Comment by mmanela** [comment]
Thanks for the details. I will attempt to reproduce and get back to you.

**Comment by mmanela** [comment]
I commited a initial fix that allows your project to run tests without error in VS. The issue is that your DEEP node_modules paths overflow 255 characters which will cause .net to throw errors. I am not handling those errors as a stop-gap solution.

Longer term solution I want to enforce that you always have a chutzpah.json file so that I can rely on that when setting up file watchers in VS.
