### ISSUE TITLE
VS2015 not getting references with chutzpah context menu extension 4.1.0

### ISSUE THREAD

**Issue by Aberwyvern** [mmanela/chutzpah#398]
In the latest version (4.1) of the extension the <reference tags in the .Spec files are not being respected when run through Chutzpah context menu extensions in VS2015. They do work in VS2013

__Quick Reproduction__
A simple solution illustrating the problem can be downloaded here : 
https://drive.google.com/file/d/0B4Cj_jU0LeE6bGlQdGhaandkZ1k/view?usp=sharing

If you run the .Spec file in 2013 it works. If your run the .Spec file in 2015 it fails. In Chrome dev tools you can see it didn't download the reference listed in the .Spec file.

__Detailed Reproduction__
To do the steps manually:

(1) Create a VS2013 web project

(2) Add a scripts folder

(3) In the scripts folder add MyLibrary.js with the following contents
```
var myModule = window.myModule || {};
myModule.myLib = function () {
	return {
		saySomething: function () { return "Hello World"; }
	}
}();
```

(4) In the scripts folder add Chutzpah.json with the following contents:
```
{
	"RootReferencePathMode": "SettingsFileDirectory",
	"TestFileTimeout": 120000,
	"FrameworkVersion": "1",
	"References": [
		{ "Path": "//cdnjs.cloudflare.com/ajax/libs/jasmine/1.3.1/jasmine.js", "IsTestFrameworkFile": "true" },
		{ "Path": "//cdnjs.cloudflare.com/ajax/libs/jasmine/1.3.1/jasmine-html.js", "IsTestFrameworkFile": "true" }
	],
	"CodeCoverageExcludes": [
		"*\\*.Spec.*"
	],
	"Tests": [
		{ "Path": "Tests", "Include": "*.Spec.*" }
	]
}
```

(5) Create a "Tests" folder within the "Scripts" folder

(6) In the tests folder add MyLibrary.Spec.js with the following contents
```
/// <reference path="../MyLibrary.js" />

describe('ChutzpahTest', function () {
	it("say something", function () {
		expect(myModule.myLib.saySomething).toBeDefined("Hello World");
	});
});
```

**Comment by mmanela** [comment]
Thanks. I made a breaking change and I need to document it better. Chutzpah originally didn't have the JSON file and would only find references by cracking open your file and parsing for reference comments. However, with the JSON file existing the recommended way for declaring references is to us the reference section and not the file comments (since there is a perf hit in parsing the files). As part of this release I made a change that by default we do not part the comments if you specify your test files in the chutzpah.json file. However, if you still want that behavior you can set the ExpandReferenceComments setting to true.

```
	"Tests": [
		{ "Path": "Tests", "Include": "*.Spec.*", "ExpandReferenceComments":  "true" }
	]
```
