### ISSUE TITLE
With release v4.1.0, no "/// <reference ...>" statements are being picked up

### ISSUE THREAD

**Issue by robertsimmons** [mmanela/chutzpah#399]
No code or project changes, and both extensions have stopped successfully running tests (Test Adapter and Context Menu versions). It appears that any/all work happening in a referenced file isn't being executed. Using VS2015. The only change at all has been the chtuzpah extension updates.

If I fall back to 4.0.3, everything works fine again, with no other changes.

Sample project I was testing with here: https://github.com/robertsimmons/ChutzpahTest

**Comment by mmanela** [comment]
Chutzpah 4.1 made a change to when it will scan your file for ```/// <reference``` comments.  Originally, Chutzpah did not have the chutzpah.json settings file and would only find references by cracking open your file and parsing for reference comments. However, since the chutzpah.json file was added the recommended way for declaring references is to use the reference section and not the file comments. The problem was that even if you used a chutzpah.json it would still open your files and parse them for the comments (which has a performance cost). In order to solve this problem version 4.1 changes the way expanding references works.

1. If you do not use a chutzpah.json file to specify your tests (NOT RECOMMENDED), then nothing changes. Your reference comments are still parsed.

2. If you specify a tests setting AND want to still expand nested references must set the ```ExpandReferenceComments``` setting to true. For example:

```
	"Tests": [
		{ "Path": "Tests", "Include": "*.Spec.*", "ExpandReferenceComments":  "true" }
	]
```

**Comment by robertsimmons** [comment]
Thank you - I was unable to find any notes about breaking changes for 4.1, so wasn't sure what was going on. Everything is working now on the new version.

**Comment by mmanela** [comment]
Thanks, I didn't do a good enough job to document this change. I added a notice to the main page and include it in the 4.1 release notes.
