### ISSUE TITLE
Supply own Jasmine libraries option

### ISSUE THREAD

**Issue by Smenus** [mmanela/chutzpah#416]
Hello!

I've just set up Chutzpah on a TypeScript project, and I'm loving it so far!

One thing I have noticed, and was wondering if something could be added for it, is that the provided version of Jasmine (and presumably Mocha and QUnit) sometimes lags behind the version that bower will bring in. In our project we had a separate test runner HTML file, that we were initially using for tests, and obviously there we could bring in the latest versions of everything (so we might end up using things provided by the later versions).

I was thinking that maybe there could be a way to specify that certain references will override the built in testing libraries. When something like that is done, it's obviously down to the user to make sure they reference everything.

I guess I could try and fake it by making a custom harness file, or by replacing Jasmine in the extension installation, but something more official would be nicer.

Is this something I can already do, or is this something worth pursuing do you think?

**Comment by mmanela** [comment]
You are correct that you can accomplish this with a custom test harness but I tend to discourage people from doing that unless they need to since then you lose some of the value Chutzpah is providing. 

I have heard this feedback before of people want to choose their explicit version of QUnit/Jasmine and it is a very reasonable request. I have dragged my feet on it in the past though since I was afraid of compatibility issues. New versions of those libraries can sometimes break Chutzpah unless a compensating change is made. But maybe it is worth it to expose the option with a disclaimer about that potential issue?

What do you think?

**Comment by Smenus** [comment]
I think a disclaimer that this option could cause issues (like with the custom harness option) would be enough for most people.
Maybe something like Karma's options - where you list the frameworks that you want it to deal with, or include the files yourself in the files array.

**Comment by flyer1** [comment]
This is the only issue that concerns me - that the embedded references (mocha in our case) lag behind too much and therefore some of the newer features/fixes are not available to us or at the very least the documentation we read about on the mocha website is out of synch with what our testing infrastructure can provide. B/c as far as I can tell, mocha v 2.1.0 is currently being used, which was released in dec of 2014. Other than that, love this VS extension!!!!

**Comment by mmanela** [comment]
I just published version 2.4.1 that upgrades to Mocha 2.4.5

**Comment by leodutra-aurea** [comment]
What about nowadays. Is it ok to reference a new version of mocha directly?
Mocha is 5.2.0 right now.
