### ISSUE TITLE
Support running multiple test harnesses within single phantom JS instance

### ISSUE THREAD

**Issue by debdasgupta** [mmanela/chutzpah#418]
It would be nice if I could run multiple test harnesses within a single phantom JS instance.  That would provide a performance improvement by saving the work of starting and stopping phantom for each test harness.  Each test harness would be a separate page load in the single phantom instance.  Ideally this would work in concert with the parallelism option, so that I have one phantom instance per processor.

I have looked into the batching option that is currently available, and it does not provide me with the flexibility that I want.  With batching, it appears that I need to define a single set of references for all of the test files in my batch.  I prefer to have each test have only the minimal set of references needed to run successfully, so that the tests remain small and targeted.  As far as I can tell, this is not possible with batching.  The set of references would need to be the superset of the references for all of the tests in the batch, so that all the tests can run within the same harness.

**Comment by mmanela** [comment]
You can accomplish this today with the batching feature (this is what I am doing in my day job). What you do is create multiple chutzpah.json files. Chutzpah will batch at the granularity of each of those files. You can even have a child chutzpah.json inherit from a parent in order to share comment referenced files. 

Try that out and if you have trouble I can build a sample when I get some free time.
