### ISSUE TITLE
Chutzpah fails build with empty test, but locally marks test as pass

### ISSUE THREAD

**Issue by bluerv** [mmanela/chutzpah#431]
Workaround is obvious... mark the test with "xit".  But...

Given a test with no expectations:

describe("Empty Test", function () {
    it("should fail", function () {
    });
});

Locally, this test passes (context menu):

1 passed, 0 failed, 1 total (chutzpah).

========== Total Tests: 1 passed, 0 failed, 1 total ==========

And it passes in the text explorer as well:

Test Name:	Empty Test should fail
Test FullName:	d:\2012devel\..\branches\dev\...\tests\...\controllers\temporarytest.js::empty test::should fail
Test Source:	d:\2012devel\...\branches\dev\...\tests\...\controllers\temporarytest.js : line 3
Test Outcome:	Passed
Test Duration:	0:00:00.002

On the server, however, this test causes the build to fail:

Error: Spec 'Empty Test should fail' has no expectations.
at specDone in file:///C:/Builds/5/.../src/packages/Chutzpah.4.1.0/tools/TestFiles/jasmine/v2/jasmine-html.js (line 105)
While Running:C:\Builds\5...\bin\_PublishedWebsites\...\Tests\...\controllers\TemporaryTest.js

Note:  The failure does show up, on careful inspection, when run locally but only through the "Run JS Tests" context menu.  Unfortunately, in long test runs, it will be obscured by the other tests, and by the final test status (above).  However, there is no indication of a problem in the Test Explorer.  

Recommendation:  Mark the test as failed, or change the message to "Warning" in the output.

**Comment by mmanela** [comment]
So the issue seems that Jasmine reports that the test PASSES to Chutzpah but then logs an error after. So when Chutzpah is running it first reports the test as passed and then get a regular error logged message saying some error happened. I can look at making this better but I would need to somehow correlate the error with the test OR sniff that explicit error message to make it a warning.

**Comment by ravikagit** [comment]
Is this issue fixed?

**Comment by mmanela** [comment]
No. The build is failing because Chutzpah is exiting with a non-zero error code. I think this error is reported in the console in VS. 

I have no looked into if there is a easy way to fix this.

**Comment by laxmiakntkalkote** [comment]
Hello ,

Have you found any solution to this?

we are facing same problem.

to avoid this shall we have any other way using spyOn function?

**Comment by bluerv** [comment]
Yes and no. The problem is deep in the structure of jasmine (if I recall correctly), so truly fixing it is going to be challenging.
However, there is a bit of a work-around.  Instead of using the Test Runner, because it effectively hides the problem, you need to use the context test runner (right click on the project to run the tests... this is a separate plug in, so make sure you have both of them to get the context menu).
The tests will then run in the output window and then you can see the errors to fix them.  It is unfortunate that it requires this extra step, but, at least there's a way to see the issue.
Hope that helps!
Sent from Yahoo Mail on Android 
 
  On Wed, Mar 16, 2016 at 10:18 AM, laxmiakntkalkote<notifications@github.com> wrote:   
Hello ,

Have you found any solution to this?

we are facing same problem.

to avoid this shall we have any other way using spyOn function?

**Comment by laxmiakntkalkote** [comment]
Thanks for quick response sir...

Actually we have facing one more issue related this...

we have void functions in js file.

so we want to achieve code coverage with the help of chutzpa .

we used only expect() n we r not comparing anything because that function is void.
for instancce expect($scope.onclick)

Test is running successfully but while taking build giving same error  "Error: Spec 'Empty Test should fail' has no expectations." 

so could you tell me way to avoid message during build and is there way to handle void functions in jasmine?

Thanks in advance...

**Comment by bluerv** [comment]
If I"m understanding correctly, you're just looking to ensure that no exceptions are thrown during the unit tests.  (If that's not right, then I'm not sure what exactly you're testing?)
If that's the case, just put an expect(true); and the jasmine test runner will stop complaining (and it will never fail due to a failed expectation obviously).

Sent from Yahoo Mail on Android 
 
  On Wed, Mar 16, 2016 at 11:04 AM, laxmiakntkalkote<notifications@github.com> wrote:   
Thanks for quick response sir...

Actually we have facing one more issue related this...

we have void functions in js file.

so we want to achieve code coverage with the help of chutzpa .

we used only expect() n we r not comparing anything because that function is void.
for instancce expect($scope.onclick)

Test is running successfully but while taking build giving same error "Error: Spec 'Empty Test should fail' has no expectations." 

so could you tell me way to avoid message during build and is there way to handle void functions in jasmine?

Thanks in advance...

**Comment by laxmiakntkalkote** [comment]
Again thanks for quick response..

See we have one angular js file save.js in this we have define Modue :

angular.module('app').controller('appController', [
    '$rootScope', '$scope', '$state', '$log')]

in this we have two functions:

function save()
{ some code }

$scope.onclick = function()
{
save()
}
 
Now we have other js file to test this file:
appTest.js

describe('appController', function () {

    var _$controller = null;
    var _$scope = null;
    var _RootScope;
    var $demandHistoryApi;
    var rest;

    beforeEach(inject(function (_$rootScope_, _$controller_, $injector) {
        _$controller = _$controller_;
        _RootScope = _$rootScope_;
        _$scope = _RootScope.$new();
        $demandHistoryApi = $injector.get('DemandHistoryApi');
        _$controller('DemandHistoryController', { $scope: _$scope, demandHistoryApi: $demandHistoryApi });
        //_$scope.value = false;
        //_$scope.test = function () {
        //    _$scope.value = true;
        //}
       _$scope.result = null;
    }));

     it('click function', function () {

      expect(_$scope.onclick );
});

Above code runs successfully but at time of build it is giving  Error: Spec 'Empty Test should fail' has no expectations."

  expect(_$scope.onclick ); //->(because of this i am getting code coverage also but i am not       setting any toEqual() to function because it is a void function . So that it is giving me above error)

So how do i fix this so that i can get code coverage also and i will not get error message also?

Please help me for this..

Thanks in advance...

**Comment by tevert** [comment]
We have a slightly different use case that is tripping over the same problem. We have tests that look like this:

```
it('does not provide a successful promise', () => {
    result.then((data) => {
        fail("This should not be called");
    });
});
```


The intent of the test is to verify that the "result" promise is in an errored state, and will therefore not call the handler we pass to "then". In this case, while we do not have an expectation, we *do* have a call to "fail". 

I think it is somewhat fair to say that every "it" should have some form of assertion, but that assertion does not have to be an "expect". Can you adjust the logic to consider more assertion possibilities?

**Comment by mmanela** [comment]
What is the exception you are getting. Chutzpah just runs Jasmine, Qunit or Mocha so if that library is unhappy then Chutzpah can't do much. 

Do you think Chutzpah is doing something wrong or is this an issue with Jasmine?

**Comment by mmanela** [comment]
Have not heard back so closing. Please re-open if needed.
