### ISSUE TITLE
ko is not defined Error in Chutzpah with Knockout Using Require Js

### ISSUE THREAD

**Issue by rajeshkdev** [mmanela/chutzpah#479]
I'm trying to write Unit Testing for my SPA project. Where we have used the `Durandal (Framework), Knockout (Binding) with RequireJs`. 

I have installed the Chutzpah in Visual Studio 2012.

When i run my Test for the View Model, it throws me below error, even though the knockout js and other js are loaded correctly.

> Uncaught ReferenceError: ko is not defined

**_My Json Config Code:**_

```
{
    "Framework": "jasmine",
    "TestHarnessReferenceMode": "AMD",
    "TestHarnessLocationMode": "SettingsFileAdjacent",
    "References" : [
        {"Path" : "../Scripts/require.js" },
        {"Path" : "config.js" }
    ],
    "Tests" : [
      {"Path": "tests"}
    ]
}
```

**_My Config Js Code:**_

```
require.config({
    paths: {
        'text': '../Scripts/text',
        'durandal': '../Scripts/durandal',
        'plugins': '../Scripts/durandal/plugins',
        'jquery': '../Scripts/jquery-2.1.4',
        'knockout': '../Scripts/knockout-3.3.0'
    },

    shim: {

    }
});
```

**_My FirstTest.Js Code:**_

```
define(['project/modules/Settings/Subscriber/Viewmodels/Channels'],
    function (nChannel) {
        describe("Get Channels", function () {
            it("will check the Get Channels call and result", function () {
                var disp = nChannel.getChannels().then(function () {
                    var actualResult = ko.toJS(nChannel.Channels);
                    expect(actualResult.length).toEqual(3);
                });
            });
        });
    });
```

**_ViewModel Code:**_

```
define(['plugins/dialog'], function (dialog) {
    var subscriberList = ko.observableArray(); //Getting Error here - while loading the Js for Unit Testing

    var JsQ = $; //Getting JQUERY members here. // Works good.

    //Other Logics goes here

    return {
        subscriberList : subscriberList,
        JsQ : JsQ 
    };
});
```

The Configuration for the Jquery works perfect, since knockout also same as that. But gives error. 

_Any Idea's / Suggestion why the error?_

Do i need to load the ko (knockout) separately?

**Comment by og-neth** [comment]
@rajeshkdev I am also getting the same issues but with Kendo framework. I found this article on stack overflow that has the exact setup I am using but still getting undefined errors:  http://stackoverflow.com/questions/31875652/typescript-project-with-unit-tests-problems-running-tests-with-chutzpah

**Comment by og-neth** [comment]
@rajeshkdev  hey this worked for me, you should load your kendo and jquery or other dependencies before require.js, here is my chutzpah.json file

```
{
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": true,
  "Tests": [
    {
      "Path": "Scripts/app"    }
  ],
  "References": [
    {
      "Path": "../Myherbalife3.Crm.AdminTool.Web/Scripts/vendors/jquery-1.10.2.min.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "../Myherbalife3.Crm.AdminTool.Web/Scripts/vendors/kendo/kendo.all.min.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "require-2.1.22.min.js",
      "IsTestFrameworkFile": true
    }
  ]
}
```

**Comment by mmanela** [comment]
@og-neth Thanks for helping. That is exactly what I would going to suggest :)

**Comment by rajeshkdev** [comment]
Many Thanks for you reply and suggestions @og-neth and @mmanela. I have tried this. The problem i found with the issue is, when there is a declaration for knockout in that file i'm not getting error like this. But without declaration if we refer the ko instance variable, its give the error. Same way we have few global declarations all around the projects.

If i use like this, inside `viewmodel `this works...

`define(['knockout', 'plugins/dialog'], function (ko, dialog) {`

But when i use like this, throws error.

```
define(['plugins/dialog'], function (dialog) {

    blades = ko.observableArray();
    blade = function (pages, button, width) {
```

This should work, since we load this instance globally to work from init.js. Code as follows

```
requirejs.config({
    paths: {
        'text': '../Scripts/text',
        'durandal': '../Scripts/durandal',
        'plugins': '../Scripts/durandal/plugins'
    }
});

define('jquery', [], function () {
    return jQuery;
});

define('knockout', [], function () {
    return ko;
});
```

Tried to load the same from `config.js` for Testing. Where as its failing here. Please suggest.

Problem is references not the declarations.

**Comment by og-neth** [comment]
@rajeshkdev I am a bit confused about your last comment, you're saying you're able to get it to work correct, if you pass in 'knockout' as a dependency to your tests? If that is the case then I don't see an issue with having your unit tests ensure they declare that 'knockout' is a dependency. My honest is advice is get your unit tests working, because after all they don't go to PROD. Your dev code architecture should be as 'DRY' as possible, but for unit tests, I don't see an issue. Also I want to clarify that in our solutions, we keep all of our unit tests (.cs and .js) in a separate project with the suffix of .Test. As long as your testing infrastructure is set up, just go with it. We do this so that our systemjs.config() is only being used by our the actual dev code, and not try to do a balancing act between tests and app js. 

Here is a sample of what my unit test looks like with my set up based on my chutzpah.json

```
//load the module(s) you wish to test, jquery and kendo already loaded as globals

define(['../../../Myherbalife3.Crm.AdminTool.Web/Scripts/app/app.clubStatistics.js'],
    function (clubStats) {
        describe('AMD chutzpah test', function () {
            it('pageProcessing initially should be set to true', function () {
                expect(clubStats.viewModel.pageProcessing).toBe(false);
            })
    })
});
```

**Comment by mmanela** [comment]
@rajeshkdev Any update? Did you resolve your issue?

**Comment by gregveres** [comment]
HI Guys

I just finished porting our code base over from no modules to using requireJS. We use typescript and knockout. And our backend is ASP.Net MVC, so we are using RequireJsNet to help us create multi-page applications in TS. 

With a little help from Mathew, I was able to get all this working great. Here are some important notes while it is all still fresh in my head:

- TS can't import modules across Visual Studio projects so I had to move all my unit tests into the main project (originally they were in their own VS project). 

- The directory Structure is Scripts/App and Scripts/Test

- I load jQuery and Knockout using MVC's bundle mechanism so I am loading them outside of requireJS. But some other libraries need to reference them as requirements. This led me to create FakejQuery.js and FakeKnockout.js - these files just define the module and export the global symbol:

```
 define('jquery', [], function () {
    return jQuery;
});
```
and
```
define('knockout', [], function () {
    return ko;
});
```
I see you put these in your requireJS config, which is also a good place to put them. 

- My unit tests import as little as possible so that I know that the main code files are defining the proper dependencies. If I get a symbol not found type error when running my unit tests, I know that the main app would get the same error. 

- Here is what my Chutzpah.json looks like:
```
{
  "Framework": "jasmine",
  "TestHarnessReferenceMode": "AMD",
  "TestHarnessLocationMode": "SettingsFileAdjacent",
  "EnableTestFileBatching": true,
  "AMDBaseUrl": "",
  "AMDAppDirectory": "",
  "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "UseSourceMaps": true
  },
  "References": [
    {
      "Path": "jquery-1.10.2.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "bootstrap.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "knockout-3.4.0.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Libs/messenger/messenger.min.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Tests/Libs/mock-ajax.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Tests/Libs/jasmine-jquery.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Components/RequireJS/require.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Tests/requireConfig.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Tests/Localization_Strings.js",
      "IsTestFrameworkFile": true
    }
  ],
  "Tests": [
    {
      "Path": "Tests",
      "Includes": [ "*/Tests/*.ts" ],
      "Excludes": [ "*/Tests/*.d.ts" ]
    }
  ],
  "CodeCoverageIncludes": [
    "*CourtGroups.*",
    "*Schedule.*",
    "*FrontDesk.*",
    "*RemoveMemberFromLeagueViewModel.*",
    "*RemoveMember.*",
    "*AddMemberToLeagueViewModel.*"
  ]
}
```

Things to note:

- The references are as small as possible. I include jquery, bootstrap, knockout and Messenger because those files are part of that MVC bundle I mentioned. (Messenger is in that list only because it was written without modules in mind and I haven't had a chance to go figure out the proper shim syntax to properly export it). 

- Then there are the two unit test files I need: mock-ajax and jasmine-jasime and I don't need to include these in the app so including them in chutzpah.json makes sense.

- Then there are the two files for requireJS. The second is my configuration object definition. 

- The last file is just a kludge for internationalisation.

I think that covers everything I ran into. I don't know if it helps or not, hopefully there was something of interest. 

Greg

**Comment by gregveres** [comment]
@rajeshkdev I know this thread is pretty old, but reading through it, I think I might know what is causing your failure. 

knockout will define itself differently if it detects requireJS. I notice in your last post that you are saying that this works: 

`define(['knockout', 'plugins/dialog'], function (ko, dialog) {
     blades = ko.observableArray();
    blade = function (pages, button, width) {;
`
but this doesn't work:

```
define(['plugins/dialog'], function (dialog) {

    blades = ko.observableArray();
    blade = function (pages, button, width) {

```

I think the answer is that when knockout loaded, it detected requireJS and didn't put ko in the global namespace, because it shouldn't pollute the global namespace when being imported as a module in requireJS. The first instance doesn't work because you didn't require knockout, therefore requireJS didn't give you an instance of ko to work with. 
But in the second instance, you did require knockout so requireJS gave you the exported symbol from the module and you were able to work with it. 

I ran into this when I was doing my adoption of requireJS and noticed this behaviour in knockout and other modules that try to adapt to a requireJS world. 

You can test if this theory is correct, you should be able to load the page in the debugger and check to see if ko exists in the global namespace.

Greg

**Comment by mmanela** [comment]
Given @gregveres last comment will close this issue now but please @rajeshkdev  re-open if issue presists after his steps.
