### ISSUE TITLE
Running ES 6 tests with Chutzpah and Jasmine

### ISSUE THREAD

**Issue by abjrcode** [mmanela/chutzpah#500]
I have some tests which are written using ES 6 and using the import style. Roughly something like this:

```
import something from "path_to_js_file_i_want_to_test"

describe( ....

)
```

I am running the latest version of the Visual Studio 2013 Chutzpah plugin but it can't recognize any of the tests. It just says no tests found ?

**Comment by mmanela** [comment]
What loader are you using? Are you using requireJS? How would you run these in a browser without chutzpah?

**Comment by abjrcode** [comment]
I am not experienced with client side development so please bear with me. Not using any loaders at the moment,  just pure ES 6 syntax with `export` and `import`.

As for running the tests on the build server we are using Karma and Webpack and Babel for transpiling. But I am only interested for now running the tests on the dev machines.

**Comment by mmanela** [comment]
The same process you go through to make it work for Karma you will need to for Chutzpah. Since Chutzpah just runs your JS in the browser you need to tell Chutzpah how to run it that way. If you look at the samples directory for Chutzpah you will see some examples of this for TypeScript and REACT.

**Comment by abjrcode** [comment]
Okay. I checked the samples and I didn't know before about the chutzpah config file. I am only using Chutzpah from the Visual Studio plugin and now my question is where is the config file that controls Chutzpah plugin for Visual Studio ?

**Comment by mmanela** [comment]
It is the same chutzpah.config file, similiar to karma's config. Put it at the root of your project.

**Comment by abjrcode** [comment]
Thank you for the help.

**Comment by abjrcode** [comment]
I tried putting the chutzpah.json file in the root and I am running chutzpah exclusively from Visual Studio 2015 using the Context Menu Plugin. Chutzpah doesn't seem to find the settings file.

**Comment by mmanela** [comment]
Have you looked at the[ chutzpah samples](https://github.com/mmanela/chutzpah/tree/master/Samples) to see other examples of its usage?

**Comment by abjrcode** [comment]
Yes. but there you run it from the command line (something which I haven't tried yet). But I need to be able to run it from the context menu inside visual studio.

**Comment by mmanela** [comment]
Those samples work in all locations.

**Comment by abjrcode** [comment]
Will try to convert the sample to a visual studio project and try to run it from there. By the way. it doesn't do compilation on fly (in-memory). it needs to write the generated ES5 tests to disk right ?

**Comment by mmanela** [comment]
yes

**Comment by abjrcode** [comment]
It doesn't work unfortunately. How is the Visual Studio plugin supposed to know to translate the file and pick up the generated one as a test file ?

**Comment by mmanela** [comment]
Same as the command line client. All the VS client does it run the code from the command line client. They both use the chutzpah.json where you can describe where your compiled files are.

**Comment by sssalib42** [comment]
In my case, I use Visual Studio to transpile es6 .ts files to es6 .js files. Why? Because I use webpack and babel to bundle my project since I need to run Angular and AngularJS side by side.

This means that I'll need to use an external compile option in the chutzpah.config.json file.
Chutzpah loads the es6 .js files to the browser, and the browser doesn't understand 'import' statements since the browsers can only parse up to es5 code syntax.

To use a compile option means that I'll end up with the compile.bat overwriting the es6 .js files, which were created by my TypeScript MSBuild. This is basically an overwriting mess, which I don't want, because the state of files will be changing back and forth!

The other option, which I think is most feasible, is to use the React example from the Chutzpah samples, consuming the es6 .js files by babel, and outputting them with a different naming convention, adding ending all files with say .chutzpah.js, which in this case the VS Chutzpah runner will freakout since it's expecting the same name, as far as I could observe.
