### ISSUE TITLE
error can't find variable in test file 

### ISSUE THREAD

**Issue by JospehMDGC** [mmanela/chutzpah#510]
working in a new project with jasmine + chutzpah + typescript in visual studio 2015 and have run into a issue that is kinda tricky

example

**file_to_be_tested.ts**

```
module Someclass
{
    export interface someother extends graphics


}
```

**testing_file.ts**

```
//ref path to tested.ts

var test: Someclass.someother

describe("test"){

beforeEach()

test = new Someclass.someother


test code
}
```

the issue that is being encountered is that when the test are run in the file, the error ReferanceError cannot find variable Someclass in file is raised.

any direction on how to fix this issue would be appreciated

**Comment by mmanela** [comment]
Can you give me a full repro that I can run locally?

**Comment by gregveres** [comment]
@JospehMDGC I too am trying to get jasmine, chutzpah and typescript setup in vs2015. I am oh so close. I was wondering if you could let me know if you have been successful. 

My current situation is that Chutzpah isn't including my file_to_be_tested.ts. In fact, I can stop the execution at a point where I can get to the html file that Chutzpah creates and see that there is no include of the file_to_be_tested.ts (which is in a different project btw). If add the reference to it, then open the html file in chrome, the resulting tests are run and pass. I had this working with javascript, but now I am trying to get the same thing working with typescript. 

If you have been successful at a trivial example, I would really appreciate any pointers. In fact, I would like to then write up How To document for @mmanela on setting this stuff up in VS2015 because all his samples seem focused on running Chutzpah standalone, but the real value to me is to get this working in the browser just like any other C# unit test. Then I will focus on getting it working as part of my CI server. 

Thanks for any help or suggestions. 
BTW, I have just started to use the Compile.Mode: External and I have tsconfig.json set to compile on save. I am hoping this is the way to go. 

I am also trying to use wildcards in the References and Tests sections because I don't want to have to remember to update Chutzpah.json each time I add a new file_to_be_tested.ts or a new testing_file.ts. 

Greg

**Comment by mmanela** [comment]
@gregveres Have you looked at this sample? https://github.com/mmanela/chutzpah/tree/master/Samples/Compilation/ExternalCompile

**Comment by mmanela** [comment]
Closing since no repro was given. Please re-open if still valid
