### ISSUE TITLE
Please add support for Jest

### ISSUE THREAD

**Issue by BioGeek** [mmanela/chutzpah#525]
I want to integrate my Jest unit tests to TFS CI, but if [this Stackoverflow answer](http://stackoverflow.com/a/37462910/50065) is correct, that is currently not yet possible using Chutzpah (or any other framework).

If I could, I would implement a [new framework definition](https://github.com/mmanela/chutzpah/tree/master/Chutzpah/FrameworkDefinitions) that will include Jest in the test execution environment, but I'm afraid my C# skills aren't good enough.

Thanks for taking this suggestion into consideration.

**Comment by mmanela** [comment]
Sure this makes sense. Thanks for the suggestion.

**Comment by Vivihung** [comment]
My project also need Jest support in Chutzpah.
Is it possible that I can follow some instructions and make Chutzpah supports Jest?
(Of course with the right process before pull request...)

**Comment by mmanela** [comment]
Sure, it shouldn't be hard if you follow how it was done for Mocha. Most of the work can be pretty boilerplate (unless Jest acts very differently than QUnit, Jasmine or Mocha). 

# Steps
1. Add the require files the Jest needs to run in a [TestFiles folder](https://github.com/mmanela/chutzpah/tree/master/Chutzpah/TestFiles/Mocha). The one tricky part here is the HTML file. This is the test harness files for Chutzpah and it contains special place holders and function calls. You can model this after the Mocha.html in the folder I linked and you can use the Qunit and Jasmine ones for more examples.

2. Add a [FrameworkDefinition](https://github.com/mmanela/chutzpah/blob/master/Chutzpah/FrameworkDefinitions/MochaDefinition.cs) for Jest. 

3. Add a PhantomJS [runner file](https://github.com/mmanela/chutzpah/blob/master/Chutzpah/JSRunners/mochaRunner.js) for Jest. This can be the trickiest part since you need to make sure you get the timing working right.

4. The last piece is the [line number processor](https://github.com/mmanela/chutzpah/blob/e1b3759a4f6da63e6c9b1215cd19e909edbe2687/Chutzpah/FileProcessors/MochaLineNumberProcessor.cs) which allows Chutzpah to match test name to line number.


The nice thing about all these steps is there is plenty of examples for ways of doing this in the code base.

Let me know if that is enough to get started, and I am glad to help more.

**Comment by Vivihung** [comment]
To my knowledge, [Jest](https://facebook.github.io/jest/) does act differently than Jasmine. (I don't have experience about QUnit and Mocha)
The biggest difference I can tell is it doesn't need headless browser to run tests.
I will try to find time to dig more and see if I can make any progress.
Thanks for your instructions.

**Comment by mmanela** [comment]
So Chutzpah only runs tests in the headless browser. People have asked to add support for running in other environments but it has not been done. If Jest can be run in PhantomJS then it should be simple to integrate. If not, things gets much more interesting ;)

**Comment by Vivihung** [comment]
According to [this discussion ](https://github.com/facebook/jest/issues/139)in Jest Git respository, Jest cannot be run in browser easily. So, yeah, the integration will be very interesting and not like existed ones.

**Comment by mmanela** [comment]
Makes sense. I tend to agree with Jests' approach, if you are testing logic you should not need a real browser environment. This would be very good to add to Chutzpah but a much larger change. It has been an ask for a long time #136 and I would love to add it but never have gotten to it. It would be great if when running Chutzpah you can choose browser based environment (PhantomJS) or a Node environment with JSDOM.

**Comment by soroshsabz** [comment]
@mmanela Hi, and thanks for this library, did you any plan to start working on this feature?

**Comment by yanckst** [comment]
@mmanela Any news for this feature request?

**Comment by mmanela** [comment]
Chutzpah now supports running tests using JsDom or Chrome (beta feature) but there would be more work for Jest. I have no plans on doing this work but would welcome the contribution on top of the groundwork I laid.

**Comment by verbraucher** [comment]
+1

**Comment by VIKTORFCO** [comment]
Hi Matthew:

I have installed **Chutzpah Test Runner** and **Chutzpah Test Adapter** for Visual Studio 2017 and 2019. I have tried to run **TypeScript tests** but unfortunatelly it arises, in both versions, the following error:

_Chutzpah Error: System.OperationCanceledException: The operation was canceled.
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Chutzpah.TestRunner.BuildTestContexts(TestOptions options, List`1 scriptPathGroups, ParallelOptions parallelOptions, CancellationTokenSource cancellationSource, Int32 resultCount, ConcurrentBag`1 testContexts, ITestMethodRunnerCallback callback, TestCaseSummary overallSummary)
   at Chutzpah.TestRunner.ProcessTestPaths(IEnumerable`1 testPaths, TestOptions options, TestExecutionMode testExecutionMode, ITestMethodRunnerCallback callback, IChutzpahWebServerHost activeWebServerHost)

========== Total Tests: 0 passed, 0 failed, 0 total ==========_

No tests have been found neither executed. May you help me? Do I have to configure something in Visual Studio? Is Chutzpah available for that VS versions?

Best regards.
Víctor.
