### ISSUE TITLE
Q: Is code-coverage supported through VSTS integrated builds?

### ISSUE THREAD

**Issue by JohnWeisz** [mmanela/chutzpah#585]
*This is an awesome extension and I'm so thankful you put effort and time into working on it. I have a small **question** though.*

I'm running the latest Chutzpah release both in my Visual Studio 2015 and our integrated online build through VSTS (Visual Studio Team Services). The tests run correctly in both places, every single one of our tests pass, the outcome is identical and the test duration is comparable.

**Code coverage**

When running Chutzpah with code-coverage, *inside Visual Studio*, the HTML report opens showing the covered files, their code coverage results, as well as the average code coverage, which is **68%**, with **4499 total statements** detected. So far so good.

**Different results in VSTS build**

However, when the tests run *through VS Team Services*, I'm getting _entirely_ different reports. The code coverage reports **5 683/18 075 blocks** (~31%) and **3 459/13 535** lines (~26%). Now these are obviously wrong, as there aren't even as many lines in the covered files.

-----

My question is: does Chutzpah _not_ support integrated builds, or am I doing something wrong? On the VSTS integrated build, I have enabled the code-coverage setting.

This is the relevant part of my configuration:

```json
{
    "CodeCoverageExecutionMode": "Always",
    "CodeCoverageIncludes": [
        "_references/*.js"
    ],
    "CodeCoverageExcludes": [
        "**.tests.js",
        "**.tests.ts"
    ],
    "EnableCodeCoverage": true
}
```

And this is the command executed by the VSTS build (edited for clarity):

```
vstest.console.exe "testfile.tests.js" /Settings:"255.tmp" /EnableCodeCoverage /logger:trx /TestAdapterPath:"packages"
```

So the command certainly goes through, but the coverage that comes back is almost certainly incorrect.

**Comment by bdbvb** [comment]
I had similar issues, using the test runner in a TFS vNext build.

What I ended up doing is executing chutzpah myself via a Gulp build step (you could probably do it other ways, but the main idea is to simply do it yourself by calling chutzpah.console.exe in a script or something). I configured chutzpah (in chutzpah.json) to use the jacoco transform to spit out an xml code coverage file and to use the trx transform to spit out a trx test results file. Then in the build, I included build steps: a step to publish the test results and a step to publish the code coverage results. 

It works fine that way. (The only issue I get is when a test fails, the publishing of test results fails with a namespace error; but code coverage is still published.)

**Comment by mmanela** [comment]
Thanks for reporting this, I have no idea why it would work differently as you found but in my tests I often do exactly what @bdbvb is saying and it has worked well for me.

BTW: @JohnWeisz can you see the code coverage report and see which files or lines it is finding in VSTS build but not on the command line?

**Comment by brettjacobson** [comment]
@JohnWeisz the code coverage you're seeing is ACTUALLY a code coverage report of the *Test Adapter* C# code.  As you can, our TFS build shows the EXACT same numbers your report;
![image](https://cloud.githubusercontent.com/assets/8862834/21987763/64ebdbea-dbca-11e6-9fbf-1d34511f32f8.png)
and here is a shot of the .coverage file opened in Visual Studio to view it:
![image](https://cloud.githubusercontent.com/assets/8862834/21989985/bd29904c-dbd2-11e6-8b8c-5ab1f30867f5.png)
This is happening whenever the Code Coverage enabled checkbox is turned on in the Visual Studio Test task.
@mmanela Do you have any ideas what we may be doing wrong, such that the .coverage file is not containing the information on our JavaScript tests?
The .trx file is correct, its just the .coverage file that seems to have Test Adapter coverage, and not JavaScript coverage.

**Comment by JohnWeisz** [comment]
@mmanela 
Thanks for looking into this, much appreciated. Unfortunately, I'm unable to open the coverage files at this time, but it seems the issue is essentially identical to what @brettjacobson is experiencing.

**Comment by JohnWeisz** [comment]
@bdbvb The problem is that I'm using widgets to track code-coverage, and... frankly, I have no clue how I would go about integrating your approach into those.

**Comment by brettjacobson** [comment]
@JohnWeisz What we're doing at the moment is the following:
1. Use the Visual Studio Test task to execute our tests (for Test Assembly I actually specify the full path to the chutzpah.json file, which in turn specifies all the tests, rather than just passing a wildcard for this attribute and then the chutzpah adapter "searches" for the json file. Doing that caused chutzpah to find a whole lot more crap than we wanted).
2. *Disable* the Code Coverage Enabled flag on this task; but note, the .trx file with test results will still get uploaded to TFS as a part of this step, but NOT the coverage file
3. in chutzpah.json, specify Transforms to cause a jacoco code coverage format file to be generated.
`    {
      "Name": "jacoco",
      "Path": "..\\..\\TestResults\\ChutzpahJacoco.xml"
    },`
  You'll also need to set the "EnableCodeCoverage" key to "Always" in the json file (or possibly do as an additional command line parameter at the task level).  Because we aren't turning on the Code Coverage flag of the task, we can't use its Manual setting.
4. Add a Publish Code Coverage results task
    Specify Jacoco format for the Code Coverage Tool parameter.
   Specify the path to the xml file, we use $(Common.TestResultsDirectory)\ChutzpahJacoco.xml (you'll have to make sure your ..\\ stuff matches where it winds up).  You can experiment with this setting based on whats in your json file.
The end result will be that you'll have the Test Results show up in your build (because they came from your test task as expected), *AND* you'll get code coverage results showing up due to the additional Publish task.

I think this is a much cleaner/clearer approach than trying to use gulp task or command line task to execute the chutzpah console runner.

**Comment by JohnWeisz** [comment]
@brettjacobson Thank you, this did it. However, some files specified through `CodeCoverageIncludes` are not recognized during the VSTS build, and I'm not sure why. All referenced files are adjacent to each other, but some are only considered for coverage when doing a Visual Studio build.

**Comment by brettjacobson** [comment]
@JohnWeisz I'd spawn another issue for that piece.  But to be honest, the CodeCoverageIncludes/Excludes at the least seem flaky to me.  I bet those settings work exactly as matthew expected them to, but we just have different expectations :)

**Comment by mmanela** [comment]
@brettjacobson Can you boil this down to a simple example where the excludes/includes are working in a way you don't expect. This way I can test and see if it is a bug.

**Comment by brettjacobson** [comment]
@mmanela No I cannot :(  Its in one of our large AngularJS apps.  What's happening is, there are "test doubles" that are included with something like this:
```
    {
      "Path": "JSTests",
      "Includes": [
        "*.ts"
      ],
      "Excludes": [ "*.spec.ts" ]
    }
```
and everything runs fine.  But in the code coverage, those test doubles are being shown in the coverage list (because they were included as a reference!), but I don't want to see that coverage.
So I add this:
```
  "CodeCoverageExcludes": [
    "node_modules/*",
    "bower_components/*",
    "JSTests/**/*.spec.ts",
    "JSTests/mock/*.ts",
    "JSTests/ngTestDoubles/*.ts"
  ],
```
Prior to adding that last exclusion for ngTestDoubles, all tests pass fine.  Adding that ngTestDouble code coverage exclusion breaks most tests, with Angular injection errors because it can not locate the test double any more.  Its like the code coverage exclusion is causing the file to no longer be loaded in the HTML that is fed to PhantomJS.

**Comment by mmanela** [comment]
Can you share the whole chutzpah.json?

**Comment by brettjacobson** [comment]
I'll see what I can do, will open a new issue for it

**Comment by bussemac** [comment]
I stumbled on this thread trying to do the same thing, get real code coverage in my VSTS builds. I'm struggling with two things currently:
1) the paths, VSTS really makes this all a pain, trying to figure out where things are during the build. My Solution has two web projects, we test them independently in different steps, folder structure is `{sourceRoot\foo\foo.web\chutzpah.json}` and likewise `{sourceRoot\bar\bar.web\chutzpah.json}` For now I'm only focusing on getting Foo working, since I'm sure I can copy it over to bar once it does.

My `foo` chutzpah.json has this:

```
{
  "Tests": [
    {
      "Path": "./App/",
      "Includes": [ "*.spec.js" ]
    }
  ],
  "CustomTestHarnessPath": "./chutzpahCustomTestHarness.html",
  "TestFileTimeout": 100000,
  "CodeCoverageExcludes": [
    "*.spec.js",
    "*.factory.js",
    "squire.js",
    "*/scripts/*",
    "*testConfig.js",
    "*.en.js",
    "*.es.js",
    "*.fr.js"
  ],
  "CodeCoverageIncludes": [
    "*.js"
  ],
  "CodeCoverageExecutionMode": "Always",
  "Transforms": [
    {
      "Name": "jacoco",
      "Path": "./ChutzpahJacocoFoo.xml"
    }
  ]
}
```

In VSTS build, I've defined a step to publish results from `$(Common.TestResultsDirectory)\ChutzpahJacacoFoo.xml` but VSTS can't find anything there. _##[warning]No code coverage results were found to publish._ I've tried a bunch of different paths, but it's just unclear where the Jacaco xml file is being saved, I don't see any references to it in the log. The entire chutzpah step doesn't contain "xml" anywhere.

The tail end of the chutzpah step looks like this:

```
2017-12-19T15:59:39.4233122Z Results File: d:\a\1\s\TestResults\VssAdministrator_factoryvm-az229 2017-12-19 15_59_31.trx
2017-12-19T15:59:39.4263517Z 
2017-12-19T15:59:39.4266089Z Total tests: 545. Passed: 545. Failed: 0. Skipped: 0.
2017-12-19T15:59:39.4269053Z Test Run Successful.
2017-12-19T15:59:39.4281022Z Test execution time: 15.7485 Seconds
2017-12-19T15:59:40.5584024Z ##[section]Async Command Start: Publish test results
2017-12-19T15:59:40.6287315Z Publishing test results to test run '4201'
2017-12-19T15:59:40.6287598Z Test results remaining: 545. Test run id: 4201
2017-12-19T15:59:41.2439876Z Published Test Run : https://[removed].visualstudio.com/[removed]/_TestManagement/Runs#runId=4201&_a=runCharts
2017-12-19T15:59:41.2440434Z ##[section]Async Command End: Publish test results
2017-12-19T15:59:41.2442073Z ##[section]Finishing: Chutzpah Tests Foo
```


2) If I run chutzpah locally, just `chutzpah.console chutzpah.json` from the `Foo.Web` folder, I get the ChutzpahJacocoFoo.xml file, but Visual Studio can't load it into the code coverage tool, _"Code Coverage Analysis Engine threw exception(s): The same table 'counter' cannot be the child table in two nested relations."_ I've tried stripping the XML file down as much as possible, but I either wind up with an invalid format or it still produces the exact same error. The command line output does show my test coverage with percentages.

```
Code Coverage Results     Average Coverage: 53%
     77% for ...\foo.web\app\shared\utils\file1.js
```
```
<?xml version="1.0" encoding="UTF-8" ?>
<report name="Chutzpah Coverage">
  <package name="Chutzpah Coverage">
   <sourcefile name="...\foo.web\app\shared\utils\file1.js">
     <line nr="1" mi="0" ci="1"/> 
     <line nr="2" mi="0" ci="1"/> 
   ... many more lines ...
     <counter type="LINE" missed="17" covered="56" />
   </sourcefile>
... many more <sourcefile /> ...
</package>
  <counter type="LINE" missed="1205" covered="1358" />
</report>
```
