### ISSUE TITLE
Code Coverage exclude breaking tests with AngularJS injection

### ISSUE THREAD

**Issue by brettjacobson** [mmanela/chutzpah#600]
All of our tests pass for this AngularJS application, with code coverage enabled.  However, there are some extra files that we don't want coverage reported on, and when we specify these in the CodeCoverageExcludes block, our tests start failing, due to missing Angular dependencies.
I suspect the coverage engine is getting confused because of our slightly whacky file layout (changing file hierarchy isn't much of an option right now);  all of our tests are under a JSTests (but yes, we've actually converted to TypeScript) folder in our web project, sibling to our app/ folder where our code is.  Under the JSTests folder are our spec files in subfolders, AND we have some test helper files under there too.  There are two subfolders mocks and ngTestDoubles.  The mocks folder just contains simple classes with static methods (thus, they're never utiilzed by Angular dependency injection), while the ngTestDoubles has some "replacement" constant and value classes (that are usually dynamically loaded at runtime).  So we wind up seeing code coverage of these ngTestDoubles files, which I want to exclude from the report.
However, excluding these files via the CodeCoverageExcludes setting *seems* to cause the files to no longer be loaded in *at all*, resulting in AngularJS throwing exceptions on nearly every test because of missing dependencies.

**Comment by brettjacobson** [comment]
```
{
  "References": [
    {
      "Path": "bower_components/sinonjs/sinon.js"
    },
    {
      "Path": "bower_components/angular/angular.min.js"
    },
    {
      "Path": "bower_components/angular-ui-router/release/angular-ui-router.js"
    },
    {
      "Path": "bower_components/angular-mocks/angular-mocks.js"
    },
    {
      "Path": "bower_components/angular-sanitize/angular-sanitize.js"
    },
    {
      "Path": "bower_components/angular-animate/angular-animate.js"
    },
    {
      "Path": "bower_components/angular-bootstrap/ui-bootstrap-tpls.js"
    },
    {
      "Path": "bower_components/ui-select/dist/select.js"
    },
    {
      "Path": "bower_components/angular-toastr/dist/angular-toastr.tpls.js"
    },
    {
      "Path": "bower_components/angular-ui-grid/ui-grid.js"
    },
    {
      "Path": "bower_components/checklist-model/checklist-model.js"
    },
    {
      "Path": "bower_components/ng-tags-input/ng-tags-input.js"
    },
    {
      "Path": "app",
      "Includes": [
        "*.module.ts"
      ]
    },
    {
      "Path": "app",
      "Includes": [
        "*.ts"
      ],
      "Excludes": ["*.module.ts"]
    },
    {
      "Path": "JSTests",
      "Includes": [
        "*.ts"
      ],
      "Excludes": [ "*.spec.ts" ]
    }
  ],
  "Tests": [
    {
      "Path": "JSTests",
      "Includes": [
        "*.spec.ts"
      ]
    }
  ],
  "Framework": "jasmine",
  "TestFileTimeout": 30000,
  "CodeCoverageExecutionMode": "Always",
  "CodeCoverageExcludes": [
    "node_modules/*",
    "bower_components/*",
    "JSTests/**/*.spec.ts",
    "JSTests/mock/*.ts",
    "JSTests/ngTestDoubles/*.ts"
  ],
  "Transforms": [
    {
      "Name": "jacoco",
      "Path": "..\\..\\TestResults\\FrontEndCodeCoverage-JaCoCo.xml"
    },
    {
      "Name": "lcov",
      "Path": "FrontEndCodeCoverage.lcov"
    },
    {
      "Name": "coveragehtml",
      "Path": "..\\..\\TestResults\\FrontEndCodeCoverage.html"
    }
  ],
  "Compile": {
    "Mode": "External",
    "Extensions": [".ts"],
    "ExtensionsWithNoOutput": [".d.ts"],
    "UseSourceMaps": true
  },
  "EnableTracing": false,
  "EnableTestFileBatching": true
}
```

**Comment by brettjacobson** [comment]
FYI with tracing on, the log file shows that the ngTestDouble files are being added.  It also says
`Adding data-cover-never attribute to blanket` and these files show up in the long list of files.

**Comment by mmanela** [comment]
There is a problem I have seen before with blanket since it instruments on the fly and if you exclude some files and include others it can change the order of loading. Chutzpah has an option (although not documented yet) that lets you allow the file to still be "instrumented" so that its loaded consistently but just ignored from coverage. Can you try the "CodeCoverageIgnores" for the files you want this behavior with?

**Comment by brettjacobson** [comment]
Seems to work like a champ, putting the offender under CodeCoverageIngores keeps it out of the report and doesn't break tests, so it sounds like I'm hitting the case you describe.

Can you explain in a little more detail the difference between Exclusion and Ignoring?
My guess based on what you said is that "ignores" is a slightly-lesser-version of excludes?

**Comment by mmanela** [comment]
@brettjacobson Yes, and this reminds me of the need to document this :)

Basically, Excludes tells the coverage engine that Chutzpah uses to not even instrument the files (by this I mean re-write the files with the coverage code inside of it). This is a good thing in general since especially for large files this can be a big performance issue. However, when you let blanket instrument your file it can sometimes subtly change the loading order if you only do it for some. In many cases this is fine but depending on usage it can cause order issues. That is why I added the __CodeCoverageIgnores__. This will still allow blanket to instrument but Chutzpah will just ignore that file's coverage in its output.

**Comment by brettjacobson** [comment]
Awesome, thanks!
