### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by vodkaduongvn** [mmanela/chutzpah#682]
I am newbie with Chutzpah, recently I pull this repo and try to run test in vs 2017 pro, but there is no test found, although jasmine show all test in browser.
https://github.com/springcomp/TypeScript.Jasmine.Chutzpah.Sample

Could u please take a look this repo Manela. Thank you so much!

**Comment by gregveres** [comment]
Hi @vodkaduongvn 
There are two VS extensions that need to be installed for Chutzpah to work completely. 

Chutzpah Rest Runner Context Menu Extension

- this one will give you the right click context menus to "Run in browser". 
- this is the one that is responsible for building the html runner page, including all your code and your tests in the runner and then spawning the browser with that runner page to run your tests.
- this one has NOTHING to do with VS Test Explorer 

Chutzpah Test Adapter for the Test Explorer

- this one is the integration with VS's Test Explorer window. 
- with this one installed and enabled, you will get the tests populating the test explorer and when you do a "run all" in the test explorer window, it will run your JS/TS tests. 

Do you have both of these installed?

**Comment by gregveres** [comment]
@vodkaduongvn 

BTW, I looked at your chutzpah.json file. I too am using it for testing Typescript files.  But my .json file is quite a bit different than yours. 

Do you have VS setup to compile your TS files on save? I do. It is much easier that way. Although, now that I have moved to using webpack to bundle my TS files, I am considering switching away from it. 

But in order to get this working, let's enable that setting. Then you can change the compile section of your .json file to something like this:

```
 "Compile": {
    "Mode": "External",
    "Extensions": [ ".ts" ],
    "ExtensionsWithNoOutput": [ ".d.ts" ],
    "UseSourceMaps": true
  },
```

Also, my Tests section is quite a bit different than yours and this might be where your problem is. Start here first:

```
  "Tests": [
    {
      "Path": "Tests",
      "Includes": [ "*/Tests/*.ts" ],
      "Excludes": [ "*/Tests/*.d.ts" ]
    }
  ],
```

Notice that I am using a single *. I haven't tried the **. 
Also, I see your reference section includes all your Tests files. I don't think that is good. The reference section is for files that you need to include all the time in the test runner. I use require.js to resolve my import statements. There are some files that are needed (like jQuery) that don't come in nicely with require.js. And I want it to be included for every one of my tests, so I include it in my references section. My understanding is that this reference section should be very targeted. Here is mine:

```
 "References": [
    {
      "Path": "Libs/jquery/jquery-1.12.4.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Libs/bootstrap/bootstrap.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Libs/messenger/messenger.min.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Tests/Libs/mock-ajax.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Tests/Libs/jasmine-jquery.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Components/RequireJS/require.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Tests/requireConfig.js",
      "IsTestFrameworkFile": true
    },
    {
      "Path": "Tests/Localization_Strings.js",
      "IsTestFrameworkFile": true
    }
  ],
```

I hope that helps get you on your way.
